ALTER TABLE leads
ADD COLUMN consent_text_version VARCHAR(40) NOT NULL DEFAULT '2026-04-20-v1',
ADD COLUMN privacy_policy_version VARCHAR(40) NOT NULL DEFAULT '2026-04-20-v1',
ADD COLUMN consent_given_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
